# Generated by Django 4.2.11 on 2024-04-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('course_ordered', models.CharField(max_length=50, verbose_name='Course Ordered')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Date Paid')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Date Completed')),
                ('amount_paid', models.IntegerField(verbose_name='Amount Paid')),
                ('order_id', models.IntegerField(verbose_name='Order ID')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('order_status', models.CharField(max_length=30, verbose_name='Order Status')),
            ],
            options={
                'verbose_name': 'Online Student',
                'verbose_name_plural': 'Online Students',
                'unique_together': {('order_id', 'user_id')},
            },
        ),
    ]
