# Generated by Django 4.2.11 on 2024-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinestudents',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, verbose_name='Email'),
        ),
    ]
