# Generated by Django 4.2.11 on 2024-04-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_onlinestudents_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestudents',
            name='email',
            field=models.EmailField(default=2, max_length=40, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
