# Generated by Django 4.2.11 on 2024-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_emailtemplate_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='Email Host')),
                ('user', models.CharField(max_length=100, verbose_name='Email Host User')),
                ('password', models.CharField(max_length=100, verbose_name='Email Host Password')),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Default From Email')),
                ('port', models.IntegerField(verbose_name='Email Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Email use TLS')),
            ],
        ),
    ]
