# Generated by Django 4.2.11 on 2024-04-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_emailsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name': 'Email Settings', 'verbose_name_plural': 'Email Settings'},
        ),
    ]
